### ISSUE TITLE
Setting icon attribute to null gives error

### ISSUE THREAD

**Issue by jakemac53** [Polymer/core-icon#28]
See http://jsbin.com/nusiho/1/edit, click the button and you will see the following error in the console:

Exception caught during observer callback: TypeError: Cannot read property 'split' of null
    at core-icon.Polymer.updateAlt (http://www.polymer-project.org/components/core-icon/core-icon.html:188:50)
    at core-icon.Polymer.updateIcon (http://www.polymer-project.org/components/core-icon/core-icon.html:147:14)
    at core-icon.g.invokeMethod (http://www.polymer-project.org/components/polymer/polymer.js:13:25932)
    at core-icon.g.notifyPropertyChanges (http://www.polymer-project.org/components/polymer/polymer.js:13:24037)
    at Object.x.report_ (http://www.polymer-project.org/components/polymer/polymer.js:12:18266)
    at Object.S.check_ (http://www.polymer-project.org/components/polymer/polymer.js:12:22604)
    at c (http://www.polymer-project.org/components/polymer/polymer.js:12:12173) 

Original report here https://github.com/dart-lang/core-elements/issues/148

**Comment by benjaminapetersen** [comment]
Pinging this one, I've been seeing the same thing.  It's a bit tricky to nail down if your app has a number of icons as the stack trace doesn't indicate where the problem originates.

**Comment by Andersmholmgren** [comment]
I'm seeing this a lot too

**Comment by davenotik** [comment]
Encountered this too (old Polymer). I simply made sure that I passed an empty string where it otherwise might have been null.
